### ISSUE TITLE
training PASCAL VOC 2012

### ISSUE THREAD

**Issue by algila** [tanakataiki/ssd_kerasV2#9]
I try to train PASCAL VOC 2012 (having 20 classes) getting the below error. 
I used:
# some constants
NUM_CLASSES = 20
input_shape = (224, 224, 3)

Any idea how to solve ? The main strange think is that the last error line with the size of array change every times I run the code.
```
model_ssd_train_OLI.py:259: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 13700, 30, verbose=1, workers=1, validation_data=<generator..., callbacks=[<keras.ca..., validation_steps=3425)`
  nb_worker=1)
/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/30
Traceback (most recent call last):
  File "model_ssd_train_OLI.py", line 259, in <module>
    nb_worker=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "model_ssd_train_OLI.py", line 236, in generate
    y = self.bbox_util.assign_boxes(y)
  File "/home/alberto/Scrivania/example/ssd_kerasV2-master_OLI/ssd_utils.py", line 149, in assign_boxes
    assignment[:, 5:-8][best_iou_mask] = boxes[best_iou_idx, 4:]
ValueError: shape mismatch: value array of shape (33,22) could not be broadcast to indexing result of shape (33,3)
```

**Comment by tanakataiki** [comment]
The number of class should be classes plus   background
And input shape should be 300by300

**Comment by algila** [comment]
Hi, many thanks but it is not solving (keras 2.2.0, TF 1.8, python 2.7):
 ```
# some constants
NUM_CLASSES = 21 #n call + backgroung
input_shape = (300, 300, 3)
```

the error is the same (I copy also some warnings related to keras 2):
```
model_ssd_train_OLI.py:259: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  nb_worker=1)
model_ssd_train_OLI.py:259: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 13700, 30, verbose=1, workers=1, validation_data=<generator..., callbacks=[<keras.ca..., validation_steps=3425)`
  nb_worker=1)
/home/alberto/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/30
Traceback (most recent call last):
  File "model_ssd_train_OLI.py", line 259, in <module>
    nb_worker=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "model_ssd_train_OLI.py", line 236, in generate
    y = self.bbox_util.assign_boxes(y)
  File "/home/alberto/Scrivania/example/ssd_kerasV2-master_OLI/ssd_utils.py", line 149, in assign_boxes
    assignment[:, 5:-8][best_iou_mask] = boxes[best_iou_idx, 4:]
ValueError: shape mismatch: value array of shape (32,22) could not be broadcast to indexing result of shape (32,20)
```
If I launch again the code the last line error change as below:

`ValueError: shape mismatch: value array of shape (128,22) could not be broadcast to indexing result of shape (128,20)`

If I launch again the code the last line error change as below:

`ValueError: shape mismatch: value array of shape (69,22) could not be broadcast to indexing result of shape (69,20)`

Do you havew any idea about the array it is referring to ?

**Comment by algila** [comment]
so in the file SSD_Training
```
 # some constants
NUM_CLASSES = 20+1  class number + background 
```

while in the file `get_data_from_XML.py` at line 9
`self.num_classes = 20   #class number only`
is it correct ? 
In this way one single image is processed and the code run for some images before to stop in an other error different from the above.
